// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zgjzupjmeuvjzpwhsard.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpnanp1cGptZXV2anpwd2hzYXJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1ODg3MDIsImV4cCI6MjA1ODE2NDcwMn0.GHQ6Y4Ojz5HRZ0c2avwHBXFw130UbSSlIZWZo_bXAbM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);