// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jfqefurialkthrjnoojh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmcWVmdXJpYWxrdGhyam5vb2poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1MTM4NDcsImV4cCI6MjA1ODA4OTg0N30.av3JKKCMjvdgTpaE_DUHJhEpH0c15dinXf6iBbT3nkw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);